In [2]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Loading dataset

application=pd.read_csv("application_record.csv")
credit=pd.read_csv("credit_record.csv")

In [5]:
application.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

In [6]:
credit.head()

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

In [7]:
application.shape

(438557, 18)

In [8]:
credit.shape

(1048575, 3)

In [9]:
application.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='str')

In [10]:
credit.columns

Index(['ID', 'MONTHS_BALANCE', 'STATUS'], dtype='str')

In [11]:
application.info()

<class 'pandas.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   438557 non-null  int64
 1   CODE_GENDER          438557 non-null  str
 2   FLAG_OWN_CAR         438557 non-null  str
 3   FLAG_OWN_REALTY      438557 non-null  str
 4   CNT_CHILDREN         438557 non-null  int64
 5   AMT_INCOME_TOTAL     438557 non-null  float64
 6   NAME_INCOME_TYPE     438557 non-null  str
 7   NAME_EDUCATION_TYPE  438557 non-null  str
 8   NAME_FAMILY_STATUS   438557 non-null  str
 9   NAME_HOUSING_TYPE    438557 non-null  str
 10  DAYS_BIRTH           438557 non-null  int64
 11  DAYS_EMPLOYED        438557 non-null  int64
 12  FLAG_MOBIL           438557 non-null  int64
 13  FLAG_WORK_PHONE      438557 non-null  int64
 14  FLAG_PHONE           438557 non-null  int64
 15  FLAG_EMAIL           438557 non-null  int64
 16  OCCUPATION_TYPE      304354 non-null  str
 17  CNT_FAM_MEMBERS      438557 non-null  float64
dtypes: float64(2), int64(8), str(8)
memory usage: 60.2 MB

In [12]:
credit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   ID              1048575 non-null  int64
 1   MONTHS_BALANCE  1048575 non-null  int64
 2   STATUS          1048575 non-null  str
dtypes: int64(2), str(1)
memory usage: 24.0 MB

In [13]:
application.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,4.385570e+05,438557.000000,4.385570e+05,438557.000000,438557.000000,438557.0,438557.000000,438557.000000,438557.000000,438557.000000
mean,6.022176e+06,0.427390,1.875243e+05,-15997.904649,60563.675328,1.0,0.206133,0.287771,0.108207,2.194465
std,5.716370e+05,0.724882,1.100869e+05,4185.030007,138767.799647,0.0,0.404527,0.452724,0.310642,0.897207
min,5.008804e+06,0.000000,2.610000e+04,-25201.000000,-17531.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.609375e+06,0.000000,1.215000e+05,-19483.000000,-3103.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,6.047745e+06,0.000000,1.607805e+05,-15630.000000,-1467.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,6.456971e+06,1.000000,2.250000e+05,-12514.000000,-371.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,7.999952e+06,19.000000,6.750000e+06,-7489.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [14]:
application.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [15]:
credit.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [16]:
# Merge the application and credit datasets using the common ID column

data=pd.merge(application,credit,on='ID',how='inner')

In [17]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MONTHS_BALANCE,STATUS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0,C
1,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-1,C
2,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-2,C
3,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-3,C
4,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-4,C

In [18]:
data.shape

(777715, 20)

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 777715 entries, 0 to 777714
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   777715 non-null  int64
 1   CODE_GENDER          777715 non-null  str
 2   FLAG_OWN_CAR         777715 non-null  str
 3   FLAG_OWN_REALTY      777715 non-null  str
 4   CNT_CHILDREN         777715 non-null  int64
 5   AMT_INCOME_TOTAL     777715 non-null  float64
 6   NAME_INCOME_TYPE     777715 non-null  str
 7   NAME_EDUCATION_TYPE  777715 non-null  str
 8   NAME_FAMILY_STATUS   777715 non-null  str
 9   NAME_HOUSING_TYPE    777715 non-null  str
 10  DAYS_BIRTH           777715 non-null  int64
 11  DAYS_EMPLOYED        777715 non-null  int64
 12  FLAG_MOBIL           777715 non-null  int64
 13  FLAG_WORK_PHONE      777715 non-null  int64
 14  FLAG_PHONE           777715 non-null  int64
 15  FLAG_EMAIL           777715 non-null  int64
 16  OCCUPATION_TYPE      537667 non-null  str
 17  CNT_FAM_MEMBERS      777715 non-null  float64
 18  MONTHS_BALANCE       777715 non-null  int64
 19  STATUS               777715 non-null  str
dtypes: float64(2), int64(9), str(9)
memory usage: 118.7 MB

In [20]:
# Create target variable based on repayment status

credit['TARGET']=credit['STATUS'].apply(
    lambda x:1 if x in['2','3','4','5'] else 0
)

In [21]:
# Create one target row for each applicant

target=credit.groupby('ID')['TARGET'].max().reset_index()

In [22]:
target.head()

        ID  TARGET
0  5001711       0
1  5001712       0
2  5001713       0
3  5001714       0
4  5001715       0

In [23]:
# Merge application data with target

final_data=pd.merge(application,target,on='ID',how='inner')

In [24]:
final_data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0

In [25]:
final_data.shape

(36457, 19)

In [26]:
final_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   36457 non-null  int64
 1   CODE_GENDER          36457 non-null  str
 2   FLAG_OWN_CAR         36457 non-null  str
 3   FLAG_OWN_REALTY      36457 non-null  str
 4   CNT_CHILDREN         36457 non-null  int64
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  str
 7   NAME_EDUCATION_TYPE  36457 non-null  str
 8   NAME_FAMILY_STATUS   36457 non-null  str
 9   NAME_HOUSING_TYPE    36457 non-null  str
 10  DAYS_BIRTH           36457 non-null  int64
 11  DAYS_EMPLOYED        36457 non-null  int64
 12  FLAG_MOBIL           36457 non-null  int64
 13  FLAG_WORK_PHONE      36457 non-null  int64
 14  FLAG_PHONE           36457 non-null  int64
 15  FLAG_EMAIL           36457 non-null  int64
 16  OCCUPATION_TYPE      25134 non-null  str
 17  CNT_FAM_MEMBERS      36457 non-null  float64
 18  TARGET               36457 non-null  int64
dtypes: float64(2), int64(9), str(8)
memory usage: 5.3 MB

In [27]:
# check the size of the final dataset
print(final_data.shape)

# check missing values
print(final_data.isnull().sum())

#display the first five rows
final_data.head()

(36457, 19)
ID                         0
CODE_GENDER                0
FLAG_OWN_CAR               0
FLAG_OWN_REALTY            0
CNT_CHILDREN               0
AMT_INCOME_TOTAL           0
NAME_INCOME_TYPE           0
NAME_EDUCATION_TYPE        0
NAME_FAMILY_STATUS         0
NAME_HOUSING_TYPE          0
DAYS_BIRTH                 0
DAYS_EMPLOYED              0
FLAG_MOBIL                 0
FLAG_WORK_PHONE            0
FLAG_PHONE                 0
FLAG_EMAIL                 0
OCCUPATION_TYPE        11323
CNT_FAM_MEMBERS            0
TARGET                     0
dtype: int64

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0

In [28]:
# fill missing values in occupation_type with "unknown"

final_data['OCCUPATION_TYPE']=final_data['OCCUPATION_TYPE'].fillna('Unknown')

In [29]:
final_data['OCCUPATION_TYPE'].isnull().sum()

np.int64(0)

In [30]:
# Create AGE
final_data["AGE"] = (-final_data["DAYS_BIRTH"] / 365).astype(int)

# Replace special value
final_data["DAYS_EMPLOYED"] = final_data["DAYS_EMPLOYED"].replace(365243, 0)

# Create YEARS_EMPLOYED
final_data["YEARS_EMPLOYED"] = abs(final_data["DAYS_EMPLOYED"]) / 365

# Drop original columns
final_data.drop(["DAYS_BIRTH", "DAYS_EMPLOYED"], axis=1, inplace=True)

In [31]:
final_data.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_MOBIL',
       'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE',
       'CNT_FAM_MEMBERS', 'TARGET', 'AGE', 'YEARS_EMPLOYED'],
      dtype='str')

In [32]:
final_data.select_dtypes(include='string').columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE'],
      dtype='str')

In [33]:
from sklearn.preprocessing import LabelEncoder
import pickle

# Create Label Encoders
gender_encoder = LabelEncoder()
car_encoder = LabelEncoder()
realty_encoder = LabelEncoder()
income_encoder = LabelEncoder()
education_encoder = LabelEncoder()
family_encoder = LabelEncoder()
housing_encoder = LabelEncoder()
occupation_encoder = LabelEncoder()

# Encode categorical columns
final_data["CODE_GENDER"] = gender_encoder.fit_transform(final_data["CODE_GENDER"])

final_data["FLAG_OWN_CAR"] = car_encoder.fit_transform(final_data["FLAG_OWN_CAR"])

final_data["FLAG_OWN_REALTY"] = realty_encoder.fit_transform(final_data["FLAG_OWN_REALTY"])

final_data["NAME_INCOME_TYPE"] = income_encoder.fit_transform(final_data["NAME_INCOME_TYPE"])

final_data["NAME_EDUCATION_TYPE"] = education_encoder.fit_transform(final_data["NAME_EDUCATION_TYPE"])

final_data["NAME_FAMILY_STATUS"] = family_encoder.fit_transform(final_data["NAME_FAMILY_STATUS"])

final_data["NAME_HOUSING_TYPE"] = housing_encoder.fit_transform(final_data["NAME_HOUSING_TYPE"])

final_data["OCCUPATION_TYPE"] = occupation_encoder.fit_transform(final_data["OCCUPATION_TYPE"])

# Save all encoders
pickle.dump(gender_encoder, open("gender_encoder.pkl", "wb"))
pickle.dump(car_encoder, open("car_encoder.pkl", "wb"))
pickle.dump(realty_encoder, open("realty_encoder.pkl", "wb"))
pickle.dump(income_encoder, open("income_encoder.pkl", "wb"))
pickle.dump(education_encoder, open("education_encoder.pkl", "wb"))
pickle.dump(family_encoder, open("family_encoder.pkl", "wb"))
pickle.dump(housing_encoder, open("housing_encoder.pkl", "wb"))
pickle.dump(occupation_encoder, open("occupation_encoder.pkl", "wb"))

print("All categorical features encoded successfully!")
print("All encoders saved successfully!")

All categorical features encoded successfully!
All encoders saved successfully!

In [34]:
final_data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET,AGE,YEARS_EMPLOYED
0,5008804,1,1,1,0,427500.0,4,1,0,4,1,1,0,0,17,2.0,0,32,12.443836
1,5008805,1,1,1,0,427500.0,4,1,0,4,1,1,0,0,17,2.0,0,32,12.443836
2,5008806,1,1,1,0,112500.0,4,4,1,1,1,0,0,0,16,2.0,0,58,3.106849
3,5008808,0,0,1,0,270000.0,0,4,3,1,1,0,1,1,14,1.0,0,52,8.358904
4,5008809,0,0,1,0,270000.0,0,4,3,1,1,0,1,1,14,1.0,0,52,8.358904

In [35]:
final_data.dtypes

ID                       int64
CODE_GENDER              int64
FLAG_OWN_CAR             int64
FLAG_OWN_REALTY          int64
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE         int64
NAME_EDUCATION_TYPE      int64
NAME_FAMILY_STATUS       int64
NAME_HOUSING_TYPE        int64
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE          int64
CNT_FAM_MEMBERS        float64
TARGET                   int64
AGE                      int64
YEARS_EMPLOYED         float64
dtype: object

In [36]:
# Separate features and target

X = final_data[
    [
        "CODE_GENDER",
        "FLAG_OWN_CAR",
        "FLAG_OWN_REALTY",
        "AMT_INCOME_TOTAL",
        "NAME_INCOME_TYPE",
        "NAME_EDUCATION_TYPE",
        "NAME_FAMILY_STATUS",
        "NAME_HOUSING_TYPE",
        "OCCUPATION_TYPE",
        "CNT_FAM_MEMBERS",
        "AGE",
        "YEARS_EMPLOYED"
    ]
]

y = final_data["TARGET"]

In [37]:
print(X.columns)
print(X.shape)

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'AMT_INCOME_TOTAL',
       'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS',
       'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'AGE',
       'YEARS_EMPLOYED'],
      dtype='str')
(36457, 12)

In [38]:
# split the dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [39]:
print(X_train.columns.tolist())

['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'AGE', 'YEARS_EMPLOYED']

In [40]:
print(X.dtypes)

CODE_GENDER              int64
FLAG_OWN_CAR             int64
FLAG_OWN_REALTY          int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE         int64
NAME_EDUCATION_TYPE      int64
NAME_FAMILY_STATUS       int64
NAME_HOUSING_TYPE        int64
OCCUPATION_TYPE          int64
CNT_FAM_MEMBERS        float64
AGE                      int64
YEARS_EMPLOYED         float64
dtype: object

In [41]:
# scale the features

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
import pickle

with open(r"C:\Users\bhumi\Documents\jupyter\Credit_Card_Flask_App\scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

print("Scaler saved successfully!")

Scaler saved successfully!

In [43]:
# Train the Logistic Regression Model

from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [45]:
# Make predictions

y_pred=lr_model.predict(X_test)

In [46]:
# Import evaluation metrics

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [47]:
# calculate and display results

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9839550191991223

Confusion Matrix:
[[7175    0]
 [ 117    0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      7175
           1       0.00      0.00      0.00       117

    accuracy                           0.98      7292
   macro avg       0.49      0.50      0.50      7292
weighted avg       0.97      0.98      0.98      7292

C:\Users\bhumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bhumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\bhumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [48]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

In [49]:
# Evaluate

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

Accuracy: 0.9812122874382886

Confusion Matrix:
[[7135   40]
 [  97   20]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7175
           1       0.33      0.17      0.23       117

    accuracy                           0.98      7292
   macro avg       0.66      0.58      0.61      7292
weighted avg       0.98      0.98      0.98      7292

In [50]:
# Random Forest 

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

In [51]:
# Evaluate

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.9824465167306637

Confusion Matrix:
[[7147   28]
 [ 100   17]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7175
           1       0.38      0.15      0.21       117

    accuracy                           0.98      7292
   macro avg       0.68      0.57      0.60      7292
weighted avg       0.98      0.98      0.98      7292

In [52]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in c:\users\bhumi\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.17.1)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
#XGBoost

from xgboost import XGBClassifier

In [54]:
# Train the model

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

In [55]:
# Evaluate

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

Accuracy: 0.984092155787164

Confusion Matrix:
[[7165   10]
 [ 106   11]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7175
           1       0.52      0.09      0.16       117

    accuracy                           0.98      7292
   macro avg       0.75      0.55      0.58      7292
weighted avg       0.98      0.98      0.98      7292

In [59]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import matplotlib.pyplot as plt

# Dictionary of trained models
models = {
    "Logistic Regression": lr_model,
    "Decision Tree": dt_model,
    "Random Forest": rf_model,
    "XGBoost": xgb
}

# Store results
results = []

for model_name, model in models.items():

    # Predict
    y_pred = model.predict(X_test)

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)

    results.append({
        "Model": model_name,
        "Accuracy": round(accuracy,4),
        "Precision": round(precision,4),
        "Recall": round(recall,4),
        "F1-Score": round(f1,4)
    })

# Convert to DataFrame
results_df = pd.DataFrame(results)

print("Model Comparison")
print(results_df)

Model Comparison
                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression    0.9840     0.0000  0.0000    0.0000
1        Decision Tree    0.9812     0.3333  0.1709    0.2260
2        Random Forest    0.9824     0.3778  0.1453    0.2099
3              XGBoost    0.9841     0.5238  0.0940    0.1594

In [57]:
import pickle

# Save the trained XGBoost model
pickle.dump(xgb, open("credit_card_approval_model.pkl", "wb"))

print("Saved model expects:", xgb.n_features_in_)

Saved model expects: 12

In [58]:
import pickle

check_model = pickle.load(open("credit_card_approval_model.pkl", "rb"))
print(check_model.n_features_in_)

12